= SENG513 Final Project: IT Chat System

NOTE: This guide assumes you are using a Debian based linux distribution.
If you are using a different distribution, use the appropriate package manager for that distribution.

== Before You Start
. Install Node.js
+
. Install MongoDB

== Getting Started

. In root directory:
+
`npm install`
+
`mkdir dbstorage`
+
. Run mongodb with dbpath as the dbstorage folder you just made
+
Example: `mongod --dbpath='./dbstorage' --port 27017`
+
NOTE: You may need to add mongodb to your PATH variable
+
. Start the webserver with:
+
`node server.js`
+
. To start clients:
+
Navigate to http://localhost:3000

== Windows Users:


. Navigate to Virtualbox.org and download VirtualBox
+
https://www.virtualbox.org/wiki/Downloads
+
. Double click the installer and follow prompts to install VirtualBox.
+
. Navigate to Ubuntu (or your favorite linux flavour's) website and download the .iso
+
https://www.ubuntu.com/download/desktop
+
. Follow instructions on how to run Ubuntu on VirtualBox
+
http://www.psychocats.net/ubuntu/virtualbox

Additionally, you can also run node on Windows.

. Follow these instructions
+
http://blog.teamtreehouse.com/install-node-js-npm-windows

Alternatively, just uninstall Windows and install Linux on your computer. :)